name: trumpow
# Running 'snapcraft register <name>' is advised
version: '1.1.1'
summary: Reference client of Trumpow, a peer-to-peer digital currency like Bitcoin.
description: |
  Trumpow is a community-driven cryptocurrency that was inspired by Dogecoin. The Trumpow Core software allows anyone to operate a node in the Trumpow blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core18
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: i386
    build-for: i386

apps:
  d:
    command: trumpowd
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/trumpow/common/.trumpow/ instead of ~/snap/trumpow/current/.trumpow/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch trumpow-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1

  cli:
    command: trumpow-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: trumpow-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: test_trumpow
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is usable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  trumpow:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/trumpowppc/trumpow/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but trumpow designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/trumpowppc/trumpow/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/trumpow-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/Trumpow/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum trumpow-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep trumpow-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf trumpow-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/test_trumpow); then
        echo "Trumpow tests failed."
        return
      else
        echo "Trumpow tests passed."
      fi
      wget https://raw.githubusercontent.com/Trumpow/trumpow/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing Trumpow Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/trumpowd
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official trumpow-qt build on arm64
        install -m 0755 -D -t $CRAFT_PART_INSTALL/bin trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/trumpow-qt
      fi
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/trumpow-cli
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/trumpow-tx
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin trumpow-${SNAPCRAFT_PROJECT_VERSION}/bin/test_trumpow
      wget https://raw.githubusercontent.com/trumpowppc/trumpow/master/share/pixmaps/trumpow128.png
      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps trumpow128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
